rename ROOT to root
jarusll/keydogger pull request #6
Opened 2024-10-29 17:45 UTC by yoosif0

2024-11-10 13:27 UTC, Adiljumadil approved these changes

2024-11-10 13:27 UTC, Adiljumadil requested changes

2024-11-10 13:27 UTC, Adiljumadil commented on keydogger.c
> +        if (strncmp("USER=root", environ[i], 9) == 0)
<!-- Error while uploading Nusantara-v5.8-13-RMX1851-OFFICIAL-07062023-1929.zip -->

2025-01-01 15:09 UTC, jarusll commented on keydogger.c
> +        if (strncmp("USER=root", environ[i], 9) == 0)
Can you please explain why `ROOT` instead of `root`. I executed `sudo printenv` and it shows `USER=root`.

2025-01-12 12:17 UTC, jarusll commented on keydogger.c
> +        if (strncmp("USER=root", environ[i], 9) == 0)
I can see how stupid I am. Thank you.

2025-01-12 12:22 UTC, jarusll commented
Merged using patch

2025-01-12 12:22 UTC, closed without merging